version: '3'

services:

  clamav:
    image: clamav/clamav:latest
    restart: always
  
  ozone:
    build: .
    restart: always
    ports:
      - "3010:8080"
    depends_on:
      - clamav
    volumes:
      - ./:/app/ozone
