env_files = [
  { path = "./.env", profile = "production" },
  { path = "./.env.test", profile = "test" },
]

[tasks.run]
description = "Run user-api"
dependencies = []
command = "cargo"
args = ["run"]

[tasks.test]
description = "Run unit tests"
command = "cargo"
args = ["test"]
dependencies = []

[tasks.lint]
description = "Run lint"
command = "cargo"
args = ["clippy"]

[tasks.format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all"]
